// Regenerated by scripts/sync-content.mjs on every sync/build.
// Do not edit by hand — edit research-book/src/SUMMARY.md instead.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
