#!/usr/bin/env node
// Syncs research-book (mdBook source) into this Docusaurus site's docs/ dir.
// Reads src/SUMMARY.md for page order, copies referenced .md files, and
// stamps each with a sidebar_position so Docusaurus's autogenerated
// sidebar (see sidebars.js) follows the SUMMARY.md order.
//
// Run via `npm run sync` (also runs automatically before `start`/`build`).
// Content source dir defaults to the sibling `research-book` checkout used
// in this hub; override with CONTENT_DIR for CI (see .github/workflows/deploy.yml).

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SITE_ROOT = path.resolve(__dirname, '..');
const CONTENT_DIR = path.resolve(SITE_ROOT, process.env.CONTENT_DIR || '../research-book');
const SUMMARY_PATH = path.join(CONTENT_DIR, 'src', 'SUMMARY.md');
const DOCS_OUT = path.join(SITE_ROOT, 'docs');

if (!existsSync(SUMMARY_PATH)) {
  console.error(`[sync-content] SUMMARY.md not found at ${SUMMARY_PATH}`);
  console.error('[sync-content] Set CONTENT_DIR to point at a research-book checkout.');
  process.exit(1);
}

// Parse mdBook's SUMMARY.md for `- [Title](path.md)` entries, in order.
// Nesting/indentation is used only to preserve reading order; grouping in
// the sidebar comes from the folder structure of the linked files.
function parseSummary(markdown) {
  const entries = [];
  const linkRe = /-\s*\[(.+?)\]\((.+?)\)/;
  for (const line of markdown.split('\n')) {
    const match = line.match(linkRe);
    if (!match) continue;
    const [, title, link] = match;
    if (!link || link.startsWith('http://') || link.startsWith('https://')) continue;
    entries.push({ title: title.trim(), file: link.trim() });
  }
  return entries;
}

function withFrontmatter(content, title, position, isHomepage) {
  const slugLine = isHomepage ? `\nslug: /` : '';
  if (content.startsWith('---\n')) {
    const end = content.indexOf('\n---', 4);
    if (end !== -1) {
      const front = content.slice(4, end);
      const body = content.slice(end + 4);
      if (/^sidebar_position:/m.test(front)) return content;
      return `---\n${front}\nsidebar_position: ${position}${slugLine}\n---${body}`;
    }
  }
  return `---\ntitle: ${title}\nsidebar_position: ${position}${slugLine}\n---\n\n${content}`;
}

const entries = parseSummary(readFileSync(SUMMARY_PATH, 'utf8'));
if (entries.length === 0) {
  console.warn('[sync-content] No entries found in SUMMARY.md — nothing to sync.');
}

rmSync(DOCS_OUT, { recursive: true, force: true });
mkdirSync(DOCS_OUT, { recursive: true });

entries.forEach(({ title, file }, index) => {
  const src = path.join(CONTENT_DIR, 'src', file);
  if (!existsSync(src)) {
    console.warn(`[sync-content] Skipping missing file: ${file}`);
    return;
  }
  const dest = path.join(DOCS_OUT, file);
  mkdirSync(path.dirname(dest), { recursive: true });
  const raw = readFileSync(src, 'utf8');
  writeFileSync(dest, withFrontmatter(raw, title, index + 1, index === 0));
});

console.log(`[sync-content] Synced ${entries.length} page(s) from ${CONTENT_DIR} into docs/`);
